version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
    commit-message:
      prefix: "chore(python-deps)"
    open-pull-requests-limit: 5
    labels: ["dependencies", "python"]

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(rust-deps)"
    open-pull-requests-limit: 5
    labels: ["dependencies", "rust"]
