[package]
name = "markdown_lab_rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "markdown_lab_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.24.0", features = ["extension-module"] }
reqwest = { version = "0.12.12", features = ["blocking", "json"] }
scraper = "0.23.1"
html5ever = "0.29.1"
selectors = "0.26.0"
url = "2.5.4"
regex = "1.11.1"
thiserror = "2.0.12"
tokio = { version = "1.44.0", features = ["full"] }
futures = "0.3.31"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
rayon = "1.10.0"
