[package]
name = "markdown_lab"
version = "0.1.0"
edition = "2024"

[dependencies]
bacon = "3.11.0"
broot = "1.44.7"
flamelens = "0.3.1"
metal = "0.31.0"
tokio = { version = "1.43.0", features = ["full"] }
