name: Python CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Setup Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable

    - name: Install build dependencies
      run: pip install maturin

    - name: Install project and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev,test]

    - name: Run tests
      run: |
        python -m pytest -v --tb=short
