name: Release

on:
  push:
    tags: ["v*.*.*"]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Install uv and build tools
        run: |
          pip install uv build maturin
          uv sync
      
      - name: Build packages
        run: |
          source .venv/bin/activate
          maturin build --release
          python -m build
      
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*
            target/wheels/*
